language: cpp
compiler:
- gcc
install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test
- sudo apt-get -qq update
- sudo apt-get install -y libcurl4-openssl-dev gcc-6
- wget "https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz" -O - | tar xzf - -C .
script:
- export PATH=../cmake-3.8.0-Linux-x86_64/bin:$PATH
- mkdir build
- cd build
- cmake ..
- make
after_success:
- cp archbestmirrors ../
- cd ..
- BRANCH="master"
- if [ "$TRAVIS_BRANCH" = "$BRANCH" ]; then
-   if [ "$TRAVIS_PULL_REQUEST" = false ]; then
-     if [ -z "$TRAVIS_TAG" ]; then
-       echo -e "Starting to tag commit.\n"
-       git config --global user.email "travis@travis-ci.org"
-       git config --global user.name "Travis"
-       git tag -a v${TRAVIS_BUILD_NUMBER} -m "Travis build $TRAVIS_BUILD_NUMBER pushed a tag."
-       git push origin --tags
-       git fetch origin
-       # echo -e "Done magic with tags.\n"
-     fi
-   fi
- fi
deploy:
  provider: releases
  api_key:
    secure: TDdGr6Rni5R5mNbSq0FFevd51tGQBnaD7MbdNOxkPzcyyKxSuimNDepTwiV5QWfIfWtcZSLbSVwVPxeNCG700ZFBPSm0ZJDwuNYJ+662wMZiUPUXu2IrKSNhuvzHND6biwihBtYnv1UD3KBxy81eyStHb22b/OlSrRBDFFBV8O+LUcWgqlqNS8UgLq0areoXGu+7eiuP+iQbPfmzRUiKGhXgvbcTTrencEisVURd714OrZWYeQILC0Fvo5LYoL9/tKTRt4F5IX487us/mwkZJJ5jFpKleyXQzGKnqbkPq2EaGKCjhYX3nReswxOiESbcUz9BC91ZcXJkSyjw1Gq1KzdlT01CL4jd7FrcxtCX+zHIwDsBQgikq4y56jbfUJ0J8mgnEc3jc5ybEV/3mfbU2wNagaPbqGqndL0Hh4AsDCBZNEo0ORRxqS6Ar2d1x5AzdsSap7wxazhzYtrCPy2DV0omLaS2o0UA2oC09yMI2Y5p0khEhge2i95ISwdgHm1BBPsiXAhnfjUyCfRvLhdwlJhV1MqZktGtEJEimdELfd54P1WsnvwGBucDJkb5ms5ERHINU5beGxZUHJSiIN/ZIC33PufyxEUzvOZqHdDvdPeLB/MeEXi9sU2P2VEDAojZOrmxbFN8HMSHsvtfZeBkXKkKC3xsYKjFUS0XqgPrVWI=
  file: archbestmirrors
  skip_cleanup: true
  on:
    branch: master
    repo: ReinForce-II/archbestmirrors-cpp
